name: Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run Jeykll
        run: docker-compose -f "docker-compose.yml" up -d --build
      # Setup git
      - name: Setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      # Generate the pdf using chrome
      - name: Generate the pdf
        run: |
          curl http://127.0.0.1:4000/
          rm cv.pdf
          docker run \
          -v ${{ github.workspace }}:/usr/src/app \
          zenika/alpine-chrome --no-sandbox --print-to-pdf-no-header --print-to-pdf=cv.pdf --hide-scrollbars \
          http://jekyll:4000/
      # Commit the generated pdf
      - name: Commit
        run: |
          sudo chown runner:docker cv.pdf
          # Stage the file, commit and push
          git add cv.pdf
          git commit -m "generated pdf"
          git push origin master
      - uses: actions/upload-artifact@v2
        with:
          name: cv
          path: cv.pdf
      - name: Stop Jeykll
        run: docker-compose -f "docker-compose.yml" down
        
        
    
    
