name: github pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      # Builds the html using hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Build Hugo
        run: hugo --minify
      # Hosts the html using docker/nginx
      - name: Bring up nginx
        run: docker-compose -f "docker-compose.yml" up -d && docker-compose start http
      - name: Wait for nginx
        run: |
          attempt_counter=0
          max_attempts=5

          until $(curl --output /dev/null --silent --head --fail http://localhost/cv); do
              if [ ${attempt_counter} -eq ${max_attempts} ];then
                echo "Max attempts reached"
                exit 1
              fi

              printf '.'
              attempt_counter=$(($attempt_counter+1))
              sleep 10
          done
      # Generate the pdf using chrome
      - name: Generate the pdf
        run: |
          sudo chown runneradmin:runneradmin public/files/cv.pdf
          docker run \
          --network container:http \
          -v ${{ github.workspace }}:/usr/src/app \
          zenika/alpine-chrome --no-sandbox --print-to-pdf-no-header --print-to-pdf=public/files/cv.pdf --hide-scrollbars \
          http://http/cv
      # Publish the generated site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - uses: actions/upload-artifact@v2
        with:
          name: cv
          path: public/files/cv.pdf
      - name: Stop Hugo
        run: docker-compose -f "docker-compose.yml" down
        
        
    
    
